swagger: '2.0'
info:
  version: 0.0.1
  title: 'Mars Rover API'
  description: REST API implementation of a NASA Mars Rovers simulation.
  contact:
    name: Filipe Velosa
    email: filipe.velosa@gmail.com
    url: 'https://github.com/fvelosa'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
host: localhost:3000
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/rovers':
    get:
      description: Returns all rovers from the system that the user has access to
      x-swagger-router-controller: rovers
      responses:
        '200':
          description: The request has succeeded
          schema:
            type: array
            items:
              $ref: '#/definitions/rover-set'
    post:
      description: Creates a rover
      x-swagger-router-controller: rovers
      parameters:
        - name: rover
          in: body
          description: Rover to add
          required: true
          schema:
            $ref: '#/definitions/new-rover'
      responses:
        '200':
          description: Resource created successfully
          schema:
            $ref: '#/definitions/rover'
  '/rovers/{id}':
    get:
      description: 'Returns a single rover'
      x-swagger-router-controller: rover
      parameters:
        - name: id
          in: path
          description: ID of rover to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: The request has succeeded
          schema:
            $ref: '#/definitions/rover'
    delete:
      description: Deletes a single rover based on the ID supplied
      x-swagger-router-controller: rover
      parameters:
        - name: id
          in: path
          description: ID of the rover to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Rover deleted
  '/rovers/{r-id}/routes':
    get:
      description: Returns all routes for a single rover that the user has access to
      x-swagger-router-controller: rover_routes
      parameters:
        - name: r-id
          in: path
          description: ID of rover to fetch
          required: true
          type: integer
          format: int64
        - name: status
          in: query
          description: status to filter by
          required: false
          type: string
        - name: size
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: Set of routes
          schema:
            $ref: '#/definitions/route-set'
    post:
      description: Creates a new route to a single rover
      x-swagger-router-controller: rover_routes
      parameters:
        - name: r-id
          in: path
          description: ID to fetch
          required: true
          type: integer
          format: int64
        - name: route
          in: body
          description: Route to add
          required: true
          schema:
            $ref: '#/definitions/new-route'
      responses:
        '200':
          description: Resource created successfully
          schema:
            $ref: '#/definitions/route'
  '/rovers/{id}/routes/{r-id}':
    get:
      description: 'Returns a single route'
      x-swagger-router-controller: rover_route
      parameters:
        - name: id
          in: path
          description: ID of rover to fetch
          required: true
          type: integer
          format: int64
        - name: r-id
          in: path
          description: ID of route to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: The request has succeeded
          schema:
            $ref: '#/definitions/route'
    delete:
      description: deletes a single route based on the ID supplied
      x-swagger-router-controller: rover_route
      parameters:
        - name: id
          in: path
          description: ID of the rover to fetch
          required: true
          type: integer
          format: int64
        - name: r-id
          in: path
          description: ID of the route to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Route deleted
    patch:
      description: 'Changes a part of a single route object'
      x-swagger-router-controller: rover_route
      parameters:
        - name: id
          in: path
          description: ID of rover to fetch
          required: true
          type: integer
          format: int64
        - name: r-id
          in: path
          description: ID of route to update
          required: true
          type: integer
          format: int64
        - name: route updates
          in: body
          description: update fields
          required: true
          schema:
            $ref: '#/definitions/route-update'
      responses:
        '200':
          description: rover required
          schema:
            $ref: '#/definitions/rover'
  '/routes/':
    get:
      description: Returns all routes the user has access to
      x-swagger-router-controller: routes
      parameters:
        - name: status
          in: query
          description: status to filter by
          required: false
          type: string
        - name: size
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/route-set'
  '/routes/{r-id}':
    get:
      description: 'Returns a single route'
      x-swagger-router-controller: route
      parameters:
        - name: r-id
          in: path
          description: ID to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/route'
    delete:
      description: deletes a single route based on the ID supplied
      x-swagger-router-controller: route
      parameters:
        - name: r-id
          in: path
          description: ID to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Route deleted
definitions:
  rover:
    type: object
    properties:
      id:
        type: integer
      x:
        type: integer
      y:
        type: integer
      direction:
        $ref: '#/definitions/direction'
  rover-set:
    type: object
    properties:
      size:
        type: integer
      total_size:
        type: integer
      contents:
        type: array
        items:
          $ref: '#/definitions/rover'
  new-rover:
    type: object
    required:
      - x
      - y
      - dir
    properties:
      x:
        type: integer
      y:
        type: integer
      dir:
        type: string
  route:
    type: object
    properties:
      id:
        type: integer
      rover_id:
        type: integer
      moves:
        type: string
  route-set:
    type: object
    properties:
      size:
        type: integer
      total_size:
        type: integer
      contents:
        type: array
        items:
          $ref: '#/definitions/route'
  route-update:
    type: object
    properties:
      op:
        type: string
        enum:
          - update
      path:
        type: string
        enum:
          - status
      content:
        $ref: '#/definitions/status'
  new-route:
    type: object
    required:
      - moves
    properties:
      moves:
        type: string
  direction:
    type: string
    enum:
      - N
      - S
      - E
      - W
  status:
    type: string
    enum:
      - planned
      - ongoing
      - completed